prgrms-web-devcourse-final-project/WEB6_8_Catfe_BE

- build.gradle.kts
- src/main/java/com/back/domain/websocket/config/WebSocketConfig.java
- src/main/java/com/back/domain/websocket/controller/WebSocketTestController.java
- src/main/java/com/back/global/entity/BaseEntity.java
- 온라인 스터디 카페 플랫폼의 실시간 채팅 기능을 위한 WebSocket + STOMP 기본 인프라 구축
- WebSocket 서버 설정 및 연결 테스트 완료
<br/>
- **WebSocket 설정 구현**
- `WebSocketConfig` 클래스 생성 및 STOMP 메시지 브로커 설정
- WebSocket 엔드포인트 `/ws` 등록 (SockJS fallback 지원)
- CORS 설정 (`setAllowedOriginPatterns("*")` - 개발환경용)
- **메시지 브로커 구성**
- `/topic`: 1:N 브로드캐스트 (방 채팅용)
- `/queue`: 1:1 메시지 (개인 DM용)  
- `/app`: 클라이언트→서버 메시지 전송 prefix
- `/user`: 개인 메시지 전용 prefix
- **헬스체크 API 구현**
- `WebSocketTestController` 생성
- `GET /api/websocket/health`: 서버 상태 확인 엔드포인트
- `GET /api/websocket/info`: WebSocket 연결 정보 제공 엔드포인트
- **패키지 구조 생성**
- `com.back.domain.websocket.config`: WebSocket 설정
- `com.back.domain.websocket.controller`: WebSocket 컨트롤러
<br/>
Closes #33 
<br/>
- **테스트 확인된 사항**
- 서버 정상 실행 확인
- 헬스체크 API 정상 응답 확인 (`/api/websocket/health`, …
> Feat: WebSocket + STOMP 기본 설정 구현 (#33)

- src/main/java/com/back/domain/study/plan/controller/StudyPlanController.java
- src/main/java/com/back/domain/study/plan/dto/StudyPlanCreateRequest.java
- src/main/java/com/back/domain/study/plan/dto/StudyPlanResponse.java
- src/main/java/com/back/domain/study/plan/entity/Color.java
- src/main/java/com/back/domain/study/plan/entity/DayOfWeek.java
- src/main/java/com/back/domain/study/plan/entity/Frequency.java
- src/main/java/com/back/domain/study/plan/entity/RepeatRule.java
- src/main/java/com/back/domain/study/plan/entity/RepeatType.java
- src/main/java/com/back/domain/study/plan/entity/StudyPlan.java
- src/main/java/com/back/domain/study/plan/entity/StudyPlanException.java
- src/main/java/com/back/domain/study/plan/entity/StudyStatus.java
- src/main/java/com/back/domain/study/plan/repository/StudyPlanRepository.java
- src/main/java/com/back/domain/study/plan/service/StudyPlanService.java
- src/main/java/com/back/domain/study/record/entity/StudyRecord.java
- src/main/java/com/back/domain/study/todo/entity/Todo.java
- src/main/java/com/back/domain/studyroom/entity/Room.java
- src/main/java/com/back/domain/user/entity/User.java
디렉토리 구조 정리 및 엔티티 구조 일부 수정
예외 테이블 추가와 플래너 관련 레이어 아키텍처만 구현
생성 삭제 기능의 작성은 시험용으로 작성되었습니다.
- todo엔티티와 record가 연결된 문제 수정
- 예외 엔티티 추가
- 변경사항에 따른 엔티티 구조 수정
- 레이어 아키텍처 뼈대만 구성
Closes #36 
-
> Feat: plan 관련 디렉토리 정리 및 엔티티 변경 및 추가 (#36)

- build.gradle.kts
- src/main/java/com/back/global/config/EmbeddedRedisConfig.java
- src/main/java/com/back/global/config/RedisConfig.java
- src/main/resources/application-dev.yml
- src/main/resources/application-test.yml
- src/test/java/com/back/RedisConnectionTest.java
- 개발/테스트 환경에서 사용할 Embedded Redis 설정 추가
- 운영 환경에서는 외부 Redis 연결을 고려할 수 있도록 구조 분리
- StringRedisTemplate을 이용해 기본 key-value 저장/조회 가능
- spring-boot-starter-data-redis 의존성 추가
- embedded-redis 의존성 추가 (개발/테스트 환경용)
- EmbeddedRedisConfig 작성 (@Profile("local","test") 적용)
- RedisConfig 작성 → 직렬화 전략 기본 설정 (String 기반)
- application.yml에 Redis 설정 항목 추가 (localhost:6379)
Closes #57
-
> Chore: Redis 설정 추가 (#57)

- src/main/java/com/back/domain/user/controller/AuthController.java
- src/main/java/com/back/domain/user/dto/LoginRequest.java
- src/main/java/com/back/domain/user/entity/User.java
- src/main/java/com/back/domain/user/service/UserService.java
- src/main/java/com/back/global/exception/ErrorCode.java
- src/main/java/com/back/global/initData/DevInitData.java
- src/test/java/com/back/domain/user/controller/AuthControllerTest.java
- src/test/java/com/back/domain/user/service/UserServiceTest.java
- 로그인 API 구현 및 테스트 작성
- 개발 환경에서 실행 시 기본 계정을 자동 생성하는 초기 데이터 추가
* `AuthController`에 `POST /api/auth/login` 추가
* username + password로 로그인
* 성공 시:
* `Authorization: Bearer {accessToken}` 헤더 발급
* `Set-Cookie: refreshToken=...; HttpOnly` 쿠키 발급
* Body에 `RsData<UserResponse>` 반환
* `UserService#login` 로직 구현
* 사용자 조회 → 비밀번호 검증 → 상태 검증(PENDING, SUSPENDED, DELETED)
* JWT Access/Refresh Token 발급 (`JwtTokenProvider`)
* Refresh Token을 HttpOnly 쿠키로 저장
* Access Token을 응답 헤더에 설정
* UserResponse 반환
* 상태별 예외 정의 (`ErrorCode`)
* 잘못된 아이디/비밀번호 → 401
* 이메일 미인증/정지 계정 → 403
* 탈퇴 계정 → 410
* Service Test (`UserServiceTest`)
* Controller Test (`AuthControllerTest`)
* 기존 회원가입 테스트와 함께 통합 검증
* `DevInitData` 추가
* 애플리케이션 실행 시 개발 환경(dev)에서 기본 계정 자동 생성
* `user1 / 12345678!` (USER)
* `user2 / 12345678!` (USER)
* `admin / …
> Feat: 로그인 API 구현 (#64)

- .github/workflows/deploy.yml
- Github Actions 워크 플로우 추가
- 환경변수 정보 github secrets에 저장
- 자동 도커 이미지 빌드 및 배포 설정
- .env에 저장된 환경변수 정보 저장
Closes #65
- 이미지 빌드 및 배포 테스트 진행예정
> Infra: 배포 자동화 구현 (#65)

- src/main/java/com/back/domain/user/controller/AuthController.java
- src/main/java/com/back/domain/user/controller/AuthControllerDocs.java
- src/main/java/com/back/domain/user/entity/UserToken.java
- src/main/java/com/back/domain/user/repository/UserTokenRepository.java
- src/main/java/com/back/domain/user/service/UserService.java
- src/main/java/com/back/global/security/JwtTokenProvider.java
- src/main/java/com/back/global/util/CookieUtil.java
- src/test/java/com/back/domain/user/controller/AuthControllerTest.java
- src/test/java/com/back/domain/user/service/UserServiceTest.java
- 로그아웃 API 구현 및 테스트 작성
- Refresh Token을 DB(`UserToken`)에 저장하도록 개선
- Swagger 명세를 인터페이스(`AuthControllerDocs`)로 분리하여 컨트롤러와 문서를 분리
* `UserToken` 엔티티 및 `UserTokenRepository`
* Refresh Token DB 저장/삭제 관리
* `UserService`
* 로그인 시: AccessToken 발급 + RefreshToken 저장/쿠키 설정
* 로그아웃 시: RefreshToken 유효성 검증 + DB 삭제 + 쿠키 만료 처리
* `CookieUtil`
* 쿠키 생성/삭제 유틸 추가 (중복 코드 제거)
* `AuthController`
* `/logout` API 구현
* Swagger 문서 어노테이션 제거 → `AuthControllerDocs` 인터페이스에서 관리
* `AuthControllerDocs`
* Swagger 명세 및 Example JSON 정리
* `UserServiceTest`
* `AuthControllerTest`
Closes #68
- Swagger 명세는 AuthControllerDocs 인터페이스로 분리하여 관리하도록 했습니다.
- 향후 Access Token 재발급 API(/api/auth/refresh) 구현 예정입니다.
> Feat: 로그아웃 API 구현 (#68)

- .github/workflows/deploy.yml
- docker-compose.yml
- src/main/java/com/back/global/config/EmbeddedRedisConfig.java
- Mac 사용자의 Redis 실행 문제 해결
- 자동 배포 워크플로우 수정
-`EmbeddedRedis`를 사용할 시, 사용자가 맥 사용자임을 체크하면 일반 Redis를 사용하도록 
- 이후, `docker-compose.yml`을 통해 `redis`를 실행
- deploy.yml 잘못된 문법 수정  
Closes #73 
-
> Fix: Redis 실행 문제 및 자동 배포 워크플로우 수정 (#73)

- src/main/java/com/back/domain/study/plan/controller/StudyPlanController.java
- src/main/java/com/back/domain/study/plan/dto/StudyPlanDeleteRequest.java
- src/main/java/com/back/domain/study/plan/dto/StudyPlanResponse.java
- src/main/java/com/back/domain/study/plan/entity/ApplyScope.java
- src/main/java/com/back/domain/study/plan/entity/RepeatRule.java
- src/main/java/com/back/domain/study/plan/entity/StudyPlanException.java
- src/main/java/com/back/domain/study/plan/repository/StudyPlanExceptionRepository.java
- src/main/java/com/back/domain/study/plan/service/StudyPlanService.java
- src/main/java/com/back/global/exception/ErrorCode.java
- 삭제 기능 구현
- 수정, 삭제 로직 통일화
- 통일화에 따른 dto 수정
- 삭제 기능 구현
- delete dto 대신 applyScope Enum 파일을 두어 이를 통해 수정/삭제 범위 결정
- 서비스 리펙토링 및 커스텀 에러 추가
- 스웨거 어노테이션 간략하게만 세팅
Closes #70 
-
> Feat : 삭제 기능 구현 + swagger 간단하게 설정 (#70)

- src/main/java/com/back/domain/user/controller/AuthController.java
- src/main/java/com/back/domain/user/controller/AuthControllerDocs.java
- src/main/java/com/back/domain/user/dto/LoginResponse.java
- src/main/java/com/back/domain/user/service/UserService.java
- src/test/java/com/back/domain/user/controller/AuthControllerTest.java
- src/test/java/com/back/domain/user/service/UserServiceTest.java
- 로그인 API 응답 구조를 수정하여 AccessToken을 응답 Body에 포함하도록 변경
- CORS 문제 줄이고 프론트 코드 단순화
* `LoginResponse` DTO(record) 추가 → `accessToken` + `UserResponse` 포함
* `UserService#login`
* AccessToken을 헤더 대신 `LoginResponse`로 반환하도록 수정
* RefreshToken은 HttpOnly 쿠키로 설정 유지
* `AuthController#login`
* 반환 타입을 `RsData<LoginResponse>`로 변경
* 테스트 코드 수정
* `UserServiceTest`: `UserResponse` → `LoginResponse` 검증으로 변경
* `AuthControllerTest`:
* `$.data.user.username` / `$.data.accessToken` 검증
* Authorization 헤더 검증 제거
Closes #82
- 추후 refreshToken 재발급 API도 동일하게 응답 Body 기반 구조로 통일 검토 필요
> Refactor: 로그인 API 응답 구조 수정 (#82)

- src/main/java/com/back/domain/user/controller/UserController.java
- src/main/java/com/back/domain/user/controller/UserControllerDocs.java
- src/main/java/com/back/domain/user/service/UserService.java
- src/main/java/com/back/global/security/oauth/CustomOAuth2UserService.java
- src/test/java/com/back/domain/user/controller/UserControllerTest.java
- src/test/java/com/back/domain/user/service/UserServiceTest.java
- 로그인한 사용자가 자신의 계정을 탈퇴할 수 있는 API 구현 및 테스트 작성
* `UserController`
* `DELETE /api/users/me` 엔드포인트 추가
* 로그인한 본인 계정만 탈퇴 가능
* `UserService`
* `deleteUser(Long userId)` 메서드 구현
* `User` 상태를 `DELETED`로 변경
* `username`, `email`, `provider`, `providerId` 마스킹 처리
* `UserProfile` 닉네임, 이미지, bio, birthDate 마스킹 처리
* `ErrorCode`
* `USER_ALREADY_DELETED`(410 Gone) 예외 코드 추가
* Swagger 문서(`UserControllerDocs`)에 회원 탈퇴 API 문서화
* 테스트 코드 작성
* `UserServiceTest` → 회원 탈퇴 성공/예외 시나리오 단위 테스트 추가
* `UserControllerTest` → 회원 탈퇴 API E2E 테스트 추가 (200, 401, 403, 410 등)
Closes #101
- 회원 탈퇴 시 실제 DB 삭제가 아닌 Soft Delete 방식 적용
- 개인정보는 마스킹 처리하여 추후 재가입 시 중복되지 않도록 함
- 추후 정책에 따라 재가입 허용/불가 여부 조정 가능
> Feat: 회원 탈퇴 API 구현 (#101)

- src/main/java/com/back/domain/user/controller/UserController.java
- src/main/java/com/back/domain/user/controller/UserControllerDocs.java
- src/main/java/com/back/domain/user/dto/ChangePasswordRequest.java
- src/main/java/com/back/domain/user/service/AuthService.java
- src/main/java/com/back/domain/user/service/UserService.java
- src/main/java/com/back/global/exception/ErrorCode.java
- src/main/java/com/back/global/util/PasswordValidator.java
- src/test/java/com/back/domain/user/controller/UserControllerTest.java
- src/test/java/com/back/domain/user/service/UserServiceTest.java
- 로그인한 사용자가 본인 계정의 비밀번호를 변경할 수 있는 API 구현
* **UserController**
* `PATCH /api/users/me/password` 엔드포인트 추가
* **UserService**
* `changePassword(Long userId, ChangePasswordRequest request)` 메서드 구현
* 소셜 로그인 회원 차단 (`USER_010`)
* 현재 비밀번호 검증 (`USER_006`)
* 새 비밀번호 정책 검증 (`USER_005`)
* 사용자 상태 검증 (`USER_009`, `USER_008`)
* **PasswordValidator (util)**
* 공통 비밀번호 정책 검증 로직 분리
* **ErrorCode**
* `USER_010`: 소셜 로그인 회원 비밀번호 변경 불가
* 성공 및 에러 응답 예시(`200, 400, 401, 403, 410, 404, 500`) 반영
* 소셜 로그인 회원 비밀번호 변경 시 `403 Forbidden (USER_010)` 예시 추가
* **UserServiceTest**
* **UserControllerTest**
Closes #102
-
> Feat: 비밀번호 변경 API 구현 (#102)

- src/main/java/com/back/domain/study/plan/repository/StudyPlanRepository.java
- src/main/java/com/back/domain/study/plan/service/StudyPlanService.java
- src/main/java/com/back/domain/study/todo/controller/TodoController.java
- src/main/java/com/back/domain/study/todo/dto/TodoRequestDto.java
- src/main/java/com/back/domain/study/todo/dto/TodoResponseDto.java
- src/main/java/com/back/domain/study/todo/entity/Todo.java
- src/main/java/com/back/domain/study/todo/repository/TodoRepository.java
- src/main/java/com/back/domain/study/todo/service/TodoService.java
- src/main/java/com/back/global/exception/ErrorCode.java
- plan 생성 시 기존 계획과 겹치는 시간대인지 검증 로직 추가
- todo CRUD 구현
- 쿼리문을 추가하여 기존 조회 기능을 재사용하지 않고 좀 더 성능적으로 개선된 조회 후 검증. 추후 조회 기능 또한 리펙토링 예정
- todo의 경우 내용만 변경하는 방식으로 현재 구현
날짜는 수정하지 못함. 대신 체크박스를 통해 상태변경이 가능하도록 하는 기능 구현
- todo의 경우 생성자 할당 방식이 아닌 from 방식을 채택.
plan은 생성자 할당 방식으로 스타일의 차이가 있음
Closes #119 
-
> Feat : plan 생성,수정 조건 추가 + todo CRUD 구현 (#119)

- src/main/java/com/back/domain/study/todo/controller/TodoController.java
- src/main/java/com/back/domain/study/todo/repository/TodoRepository.java
- src/test/java/com/back/domain/study/todo/controller/TodoControllerTest.java
- todo 테스트
- 컨트롤러 매핑 주소 변경
- 레포 정리
- 레포에서 안쓰이는 메서드 삭제
- 성공 / 실패 케이스 추가
- 상태 변경 api 주소를 /complete -> /toggle
Closes #128 
-
> Test : todo 테스트 및 일부 수정 (#128)

- .github/workflows/backend-cd.yml
- build.gradle.kts
- infra/terraform/main.tf
- infra/terraform/variables.tf
- src/main/java/com/back/global/security/SecurityConfig.java
- AWS 환경 세팅
- 무중단 배포 준비
- Blue/Green 배포 적용
- EC2 접속 시 **ghcr.io 자동 로그인** 추가  
- **환경 변수(민감 정보)** EC2에 등록하여 관리
- 자동 배포 시 **EC2 인스턴스 ID 자동 세팅**  
- 배포 대상 **도메인 정보 추가**  
- **Spring Actuator 의존성** 추가  
- **헬스 체크 엔드포인트** 인증 없이 접근 가능하도록 허용
- **변경 전**: 최신 이미지를 pull -> 기존 컨테이너 삭제 후 새 컨테이너 실행 → 다운타임 발생  
- **변경 후**: 최신 이미지를 pull -> 새로운 컨테이너 실행 → Nginx 업스트림을 새 컨테이너로 전환 → 기존 컨테이너/이미지 정리 → 다운타임 없음
Closes #120
-
> Infra: 무중단 배포 적용 (#120)

- src/main/java/com/back/domain/study/plan/controller/StudyPlanController.java
- src/main/java/com/back/domain/study/plan/dto/StudyPlanDeleteResponse.java
- src/main/java/com/back/domain/study/plan/dto/StudyPlanRequest.java
- src/main/java/com/back/domain/study/plan/dto/StudyPlanResponse.java
- src/main/java/com/back/domain/study/plan/entity/RepeatRule.java
- src/main/java/com/back/domain/study/plan/entity/RepeatRuleEmbeddable.java
- src/main/java/com/back/domain/study/plan/entity/RepeatType.java
- src/main/java/com/back/domain/study/plan/service/StudyPlanService.java
- src/test/java/com/back/domain/study/plan/controller/StudyPlanControllerTest.java
- 생성에만 적용된 byDay 자동 불러오기 수정에도 적용
- RepeatRuleEmbeddable 생성의 헬퍼 메서드 추가 -> 기존 수정 로직의 중복 제거
- 삭제 시 삭제된 계획 정보 반환하도록 수정
- 이에 따른 테스트 케이스 변경 및 검증 방식 변경
- 생성, 수정에 적용된 byDay 자동 불러오기는 WEEKLY인 경우에만 적용됨
현재 반복 기능은 매일, 매주, 매월만 제공되며
반복 주기는 1로 고정임을 전제로 구현했으나
따로 제한을 두지는 않았기 때문에 이 부분은 주의가 필요합니다.
- 수정 부분에 RepeatRuleEmbeddable 생성 코드를 헬퍼 메서드로 따로 정의했습니다
- 테스트 케이스에서 byDay검증과 삭제된 계획 정보 검증 추가
Closes #135 
-
> Fix,Refect: 수정에도 byDay 불러오기 + 수정,삭제 기능 개선 (#135)

- src/main/java/com/back/domain/studyroom/dto/RoomMemberResponse.java
- src/main/java/com/back/domain/studyroom/entity/RoomMember.java
- src/main/java/com/back/domain/studyroom/repository/RoomMemberRepository.java
- src/main/java/com/back/domain/studyroom/repository/RoomMemberRepositoryCustom.java
- src/main/java/com/back/domain/studyroom/repository/RoomMemberRepositoryImpl.java
- src/main/java/com/back/domain/studyroom/repository/RoomRepository.java
- src/main/java/com/back/domain/studyroom/repository/RoomRepositoryImpl.java
- src/main/java/com/back/domain/studyroom/service/RoomService.java
- src/main/java/com/back/global/websocket/webrtc/service/WebRTCSignalValidator.java
- src/test/java/com/back/domain/studyroom/service/RoomServiceTest.java
- src/test/java/com/back/global/websocket/webrtc/service/WebRTCSignalValidatorTest.java
Redis 연결을 위해 `RoomMember` 엔티티를 수정하던 중, RTC/채팅 관련 최신 코드가 병합되면서 충돌 및 에러가 지속적으로 발생했습니다.  
따라서 Redis까지 연동했던 작업을 초기화하고, **DB ↔ Redis 역할 분리까지만 진행**했습니다.  
주요 변경 사항:
- `RoomMember` 엔티티에서 **실시간 상태 관련 필드 제거** (Redis 이관을 위해)
- 관련 테스트 케이스 수정
- 향후 Redis 마이그레이션 파트는 `// TODO` 주석으로 처리
---
**제거된 필드**
- `isOnline`: 온라인 상태 → Redis 이관 예정
- `connectionId`: WebSocket 연결 ID → Redis 이관 예정
- `lastHeartbeat`: 마지막 하트비트 시간 → Redis 이관 예정
- `lastActiveAt`: 마지막 활동 시간 → Redis 이관 예정
**추가된 필드**
- `promotedAt`: MEMBER 이상으로 권한 변경된 시간
**의미 변경**
- `joinedAt`: 기존 = 방 입장 시간  
변경 후 = MEMBER 이상으로 승격된 시간 (Member 이상부터만 db에 권한에 대한 정보로써 저장하기 위해)
---
- `RoomMemberRepository.findByConnectionId()` 제거
- `RoomMemberRepositoryImpl.leaveRoom()` → `@Deprecated`
- `RoomMemberRepositoryImpl.disconnectAllMembers()` → `@Deprecated`
- …
> refactor: RoomMember 엔티티에서 실시간 상태 필드 제거, redis로 이관 (#96)

- src/main/java/com/back/domain/board/controller/PostController.java
- src/main/java/com/back/domain/board/controller/PostControllerDocs.java
- src/main/java/com/back/domain/board/dto/PageResponse.java
- src/main/java/com/back/domain/board/dto/PostDetailResponse.java
- src/main/java/com/back/domain/board/dto/PostListResponse.java
- src/main/java/com/back/domain/board/repository/PostRepository.java
- src/main/java/com/back/domain/board/repository/PostRepositoryCustom.java
- src/main/java/com/back/domain/board/repository/PostRepositoryImpl.java
- src/main/java/com/back/domain/board/service/PostService.java
- src/main/java/com/back/global/security/SecurityConfig.java
- src/test/java/com/back/domain/board/controller/PostControllerTest.java
- src/test/java/com/back/domain/board/service/PostServiceTest.java
* 모든 사용자가 접근 가능한 **게시글 목록 조회** 및 **게시글 단건 조회** API를 구현했습니다.
* 검색 조건, 페이징, 카테고리 필터링을 지원하고 Swagger 문서화를 포함합니다.
1. **Controller**
* `PostController`
* `GET /api/posts` : 게시글 목록 조회
* `GET /api/posts/{postId}` : 게시글 단건 조회
2. **Service**
* `PostService#getPosts`
* 키워드, 검색 타입, 카테고리, 페이징 조건으로 게시글 목록 조회
* 결과를 `PageResponse<PostListResponse>`로 변환 후 반환
* `PostService#getPost`
* 게시글 단건 조회 후 `PostDetailResponse` 반환
* 존재하지 않는 경우 `POST_NOT_FOUND` 예외 처리
3. **Repository**
* `PostRepositoryImpl`
* `searchPosts` 메서드 구현 (QueryDSL 기반)
* 검색 조건(where), 정렬(order), 카테고리 주입(injectCategories), 전체 카운트 처리 포함
4. **DTO**
* `PageResponse<T>` : 공통 페이지 응답 DTO
* `PostListResponse` : 게시글 목록 조회 응답 DTO (작성자, 카테고리, 좋아요/북마크/댓글 수 포함)
* `PostDetailResponse` : 게시글 단건 조회 응답 DTO
5. **Swagger 문서 (`PostControllerDocs`)**
* `게시글 목록 조회` …
> Feat: 게시글 다건/단건 조회 API 구현 (#131)

- src/main/java/com/back/domain/board/controller/PostController.java
- src/main/java/com/back/domain/board/controller/PostControllerDocs.java
- src/main/java/com/back/domain/board/entity/Post.java
- src/main/java/com/back/domain/board/service/PostService.java
- src/test/java/com/back/domain/board/controller/PostControllerTest.java
- src/test/java/com/back/domain/board/service/PostServiceTest.java
* 로그인한 사용자가 본인 게시글을 수정하거나 삭제할 수 있는 API를 구현했습니다.
* Controller, Service, Test, Swagger 문서화를 포함합니다.
1. **Controller**
* `PostController#updatePost`
* `PUT /api/posts/{postId}`
* 요청 DTO(`PostRequest`) + 인증 사용자(`CustomUserDetails`)
* 수정 성공 시 `200 OK` + 수정된 게시글 정보 반환
* `PostController#deletePost`
* `DELETE /api/posts/{postId}`
* 인증 사용자만 접근 가능
* 삭제 성공 시 `200 OK` + 메시지 반환
2. **Service**
* `PostService#updatePost`
* 게시글 조회 (`POST_NOT_FOUND`)
* 작성자 검증 (`POST_NO_PERMISSION`)
* 제목/내용/카테고리 업데이트
* 존재하지 않는 카테고리 포함 시 `CATEGORY_NOT_FOUND`
* `PostResponse` 반환
* `PostService#deletePost`
* 게시글 조회 (`POST_NOT_FOUND`)
* 작성자 검증 (`POST_NO_PERMISSION`)
* 게시글 삭제
3. **DTO**
* `PostRequest`, `PostResponse` 재활용
4. **Test**
* **서비스 테스트**
* 수정 성공 → 제목/내용/카테고리 변경 확인
* 수정 실패 → 게시글 없음, 작성자 아님, 카테고리 없음
* 삭제 성공 → DB에서 게시글 제거 …
> Feat: 게시글 수정 및 삭제 API 구현 (#131)

- src/main/java/com/back/domain/board/controller/CommentController.java
- src/main/java/com/back/domain/board/controller/CommentControllerDocs.java
- src/main/java/com/back/domain/board/entity/Comment.java
- src/main/java/com/back/domain/board/service/CommentService.java
- src/main/java/com/back/global/exception/ErrorCode.java
- src/test/java/com/back/domain/board/controller/CommentControllerTest.java
- src/test/java/com/back/domain/board/service/CommentServiceTest.java
* 댓글 수정 및 삭제 기능을 구현했습니다.
* Service, Controller, Swagger 문서 및 단위/통합 테스트 포함.
* `PUT /api/posts/{postId}/comments/{commentId}` → 댓글 수정
* `DELETE /api/posts/{postId}/comments/{commentId}` → 댓글 삭제
* **updateComment**
* 게시글, 댓글 조회 후 작성자 검증
* 내용 업데이트
* **deleteComment**
* 게시글, 댓글 조회 후 작성자 검증
* 댓글 삭제 처리
* `CommentRequest` → 댓글 작성 및 수정 요청 DTO 재사용
* `CommentResponse` → 수정된 내용 반영
* `Comment` 엔티티에 `updateContent` (혹은 `update`) 메서드 추가
* `COMMENT_NOT_FOUND (404)` → 존재하지 않는 댓글
* `COMMENT_NO_PERMISSION (403)` → 댓글 작성자가 아님
* `CommentControllerDocs`에 **댓글 수정/삭제 API 문서화**
* 성공/실패/예외 응답 예시 작성
* **Service Test**
* 댓글 수정 성공 / 실패 (게시글 없음, 댓글 없음, 작성자 아님)
* 댓글 삭제 성공 / 실패 (게시글 없음, 댓글 없음, 작성자 아님)
* **Controller Test (MockMvc)**
* 수정/삭제 성공
* 실패 케이스 (인증 없음, 작성자 아님, 필드 누락, 엔티티 없음 등) 검증
Closes #159
-
> Feat: 댓글 수정 및 삭제 API 구현 (#159)

- src/main/java/com/back/domain/board/controller/CommentController.java
- src/main/java/com/back/domain/board/controller/CommentControllerDocs.java
- src/main/java/com/back/domain/board/dto/AuthorResponse.java
- src/main/java/com/back/domain/board/dto/CommentListResponse.java
- src/main/java/com/back/domain/board/entity/Comment.java
- src/main/java/com/back/domain/board/repository/CommentRepository.java
- src/main/java/com/back/domain/board/repository/CommentRepositoryCustom.java
- src/main/java/com/back/domain/board/repository/CommentRepositoryImpl.java
- src/main/java/com/back/domain/board/service/CommentService.java
- src/test/java/com/back/domain/board/controller/CommentControllerTest.java
- src/test/java/com/back/domain/board/service/CommentServiceTest.java
* 특정 게시글에 등록된 댓글 목록을 조회할 수 있는 API를 구현했습니다.
* 부모 댓글 기준으로 페이징 처리하며, 각 부모 댓글에는 자식 댓글(children)이 계층 구조로 포함됩니다.
* `GET /api/posts/{postId}/comments` → 댓글 다건 조회 엔드포인트 구현
* `CommentService#getComments`
* 게시글 존재 여부 검증
* `CommentRepositoryCustom`을 통해 댓글/대댓글 조회
* `PageResponse<CommentListResponse>` 형태로 반환
* `CommentRepositoryImpl#getCommentsByPostId`
* QueryDSL 기반 구현
* 부모 댓글/자식 댓글 각각 조회
* likeCount 집계 한 번에 처리
* 부모-자식 매핑 후 Page 객체 반환
* `CommentListResponse`
* `commentId, postId, parentId, author, content, likeCount, createdAt, updatedAt, children` 필드 포함
* `@QueryProjection` 사용
* `CommentControllerDocs`에 댓글 조회 API 문서 추가
* 성공/실패/예외 응답 예시 작성
* **Service Test**
* 댓글 조회 성공 (부모+자식 구조 확인)
* 게시글 없음 예외 검증 (`POST_001`)
* **Controller Test**
* 성공 시 → 댓글 목록 + 대댓글 구조 반환 확인
* 실패 시 → 게시글 없음 (`404`), 잘못된 파라미터 …
> Feat: 댓글 조회 API 구현 (#162)

- src/main/java/com/back/domain/board/comment/controller/CommentController.java
- src/main/java/com/back/domain/board/comment/controller/CommentControllerDocs.java
- src/main/java/com/back/domain/board/comment/dto/ReplyResponse.java
- src/main/java/com/back/domain/board/comment/service/CommentService.java
- src/main/java/com/back/global/exception/ErrorCode.java
- src/test/java/com/back/domain/board/controller/CommentControllerTest.java
- src/test/java/com/back/domain/board/service/CommentServiceTest.java
* 게시글의 댓글에 대댓글(1 depth)을 작성할 수 있는 기능을 추가했습니다.
* 서비스, 컨트롤러, 테스트, Swagger 문서까지 통합 구현했습니다.
* **`POST /api/posts/{postId}/comments/{commentId}/replies`**
* 로그인한 사용자가 특정 게시글의 댓글에 대댓글을 작성할 수 있도록 구현
* 대댓글은 1단계까지만 허용 (대댓글의 대댓글 작성 불가)
* `CommentService#createReply()`
* 사용자, 게시글, 부모 댓글 조회
* 부모 댓글의 게시글 일치 및 depth 검증 로직 추가
* 검증 통과 시 `Comment` 엔티티 생성 후 저장
* `ReplyResponse`
* `commentId`, `postId`, `parentId`, `author`, `content`, `createdAt`, `updatedAt` 포함
* `ReplyResponse.from(Comment comment)` 팩토리 메서드 추가
- COMMENT_PARENT_MISMATCH: 부모 댓글이 해당 게시글에 속하지 않습니다.
- COMMENT_DEPTH_EXCEEDED: 대댓글은 한 단계까지만 작성할 수 있습니다.
- 대댓글 생성 성공 및 예외 케이스 테스트
- 대댓글 수정 성공 (updateComment)
- 대댓글 삭제 성공 (deleteComment)
- 대댓글 생성 성공/실패 케이스 테스트
- 기존 댓글 수정/삭제 API를 통한 대댓글 수정·삭제 테스트 추가
* 대댓글 생성 API 명세 추가
* 성공 및 예외 응답 예시 포함 (`201`, `400`, …
> Feat: 대댓글 생성 API 구현 (#177)

- src/main/java/com/back/domain/study/plan/service/StudyPlanService.java
- src/main/java/com/back/domain/study/record/controller/StudyRecordController.java
- src/main/java/com/back/domain/study/record/dto/StudyRecordRequestDto.java
- src/main/java/com/back/domain/study/record/dto/StudyRecordResponseDto.java
- src/main/java/com/back/domain/study/record/entity/PauseInfo.java
- src/main/java/com/back/domain/study/record/entity/StudyRecord.java
- src/main/java/com/back/domain/study/record/repository/StudyRecordRepository.java
- src/main/java/com/back/domain/study/record/service/StudyPlanService.java
- src/main/java/com/back/domain/study/record/service/StudyRecordService.java
- src/main/java/com/back/domain/study/todo/controller/TodoController.java
- src/main/java/com/back/global/exception/ErrorCode.java
- src/test/java/com/back/domain/study/record/controller/StudyRecordControllerTest.java
- 기록 생성, 조회 기능 구현
- 테스트 케이스 구현
- 생성, 조회 기능 추가
조회의 경우 오전 4시를 기준으로 조회되며
기록된 시간 범위가 이틀에 걸칠 경우 두 날짜에 조회되도록 구현
(10.2 오후 11시 ~ 10.3 오전 5시 기록 -> 10.2, 10.3 날짜 둘 다 조회됨) 
- 생성, 조회 테스트 작성
Closes #129 
- 기록의 수정, 삭제는 지원 안함을 기준으로 작성
> Feat: 학습 기록 기능+ 테스트 구현 (#129)

- src/main/java/com/back/domain/study/memo/controller/MemoController.java
- src/main/java/com/back/domain/study/memo/dto/MemoRequestDto.java
- src/main/java/com/back/domain/study/memo/dto/MemoResponseDto.java
- src/main/java/com/back/domain/study/memo/entity/Memo.java
- src/main/java/com/back/domain/study/memo/repository/MemoRepository.java
- src/main/java/com/back/domain/study/memo/service/MemoService.java
- src/main/java/com/back/global/exception/ErrorCode.java
- 메모 기능 구현
- 메모 생성 시 해당 날짜에 메모가 존재하는 경우 수정, 없으면 생성
- 삭제 기능은 인스턴스 삭제
Closes #183 
-
> Feat: 메모 기능 구현 (#183)

- .github/workflows/backend-ci.yml
- docker-compose.yml
- infra/terraform/main.tf
CI 환경(main/dev 분리), EC2 Redis 실행 방식, docker-compose 구성을 개선하여
개발·운영 환경의 일관성과 안정성을 높였습니다.
- CI 개선
- 운영환경 개선
- docker-compose 일부 수정
- main 브랜치: Redis + MySQL 실행 후 빌드 및 테스트 진행
- dev 브랜치: Redis만 실행 후 빌드 및 테스트 진행
- 분기별 job 분리로 CI 속도 및 안정성 개선
- EC2 인스턴스 재시작 시 Redis 자동 실행되도록
- 수동 재시작 불필요
- MySQL 서비스 설정 추가 (로컬 개발 환경 반영)
- Redis command 설정 제거 (`--appendonly yes` 불필요)
- 서비스 구성 정리로 로컬 환경 단순화
Closes #186 
-
> Infra: 백엔드 환경 구성 개선 (CI / EC2 Redis / docker-compose) (#186)

- src/main/java/com/back/domain/notification/controller/NotificationController.java
- src/main/java/com/back/domain/notification/dto/ActorDto.java
- src/main/java/com/back/domain/notification/dto/NotificationCreateRequest.java
- src/main/java/com/back/domain/notification/dto/NotificationItemDto.java
- src/main/java/com/back/domain/notification/dto/NotificationListResponse.java
- src/main/java/com/back/domain/notification/dto/NotificationResponse.java
- src/main/java/com/back/domain/notification/dto/NotificationWebSocketDto.java
- src/main/java/com/back/domain/notification/entity/Notification.java
- src/main/java/com/back/domain/notification/entity/NotificationStatus.java
- src/main/java/com/back/domain/notification/repository/NotificationRepository.java
- src/main/java/com/back/domain/notification/repository/NotificationRepositoryCustom.java
- src/main/java/com/back/domain/notification/repository/NotificationRepositoryImpl.java
- src/main/java/com/back/domain/notification/service/NotificationService.java
- src/main/java/com/back/global/exception/ErrorCode.java
- src/test/java/com/back/domain/notification/controller/NotificationControllerTest.java
- src/test/java/com/back/domain/notification/repository/NotificationRepositoryTest.java
- src/test/java/com/back/domain/notification/service/NotificationServiceTest.java
- src/test/java/com/back/domain/notification/service/NotificationWebSocketServiceTest.java
알림 시스템 와이어프레임 확인 후 발신자 정보 추가 및 전체 테스트 코드 작성
<br>
- **Notification 엔티티**
- `User actor` 필드 추가 (발신자 정보)
- `user` → `receiver` 변수명 변경 (수신자 명확화)
- `status` 필드 제거 (NotificationRead로 읽음 관리 통일)
- 모든 정적 팩토리 메서드에 `actor` 파라미터 추가
- **DTO 추가/수정**
- `ActorDto` 공통 DTO 생성 (발신자 정보: userId, username, profileImageUrl)
- 모든 응답 DTO에 `ActorDto` 추가
- `NotificationCreateRequest`에 `actorId` 필드 추가
- **NotificationRepositoryImpl**
- 모든 쿼리에서 `notification.user` → `notification.receiver`로 변경
- ROOM 알림 조회를 위해 RoomMember와 LEFT JOIN 추가
- **NotificationService**
- 모든 알림 생성 메서드에 `actor` 파라미터 추가
- `validateActorAndReceiver()` 검증 메서드 추가 (자기 자신에게 알림 방지)
- `markAsRead()` 강화
- 접근 권한 검증 (`isVisibleToUser`)
- 이미 읽은 알림 체크 시 예외 발생 (`NOTIFICATION_ALREADY_READ`)
- **NotificationController**
- Request 검증 로직 추가
- targetType 유효성 검증
- …
> Test: 알림 시스템 기본 인프라 테스트 (#155)

- src/main/java/com/back/domain/board/post/controller/PostCategoryController.java
- src/main/java/com/back/domain/board/post/controller/PostCategoryControllerDocs.java
- src/main/java/com/back/domain/board/post/dto/CategoryRequest.java
- src/main/java/com/back/domain/board/post/dto/CategoryResponse.java
- src/main/java/com/back/domain/board/post/entity/PostCategory.java
- src/main/java/com/back/domain/board/post/enums/CategoryType.java
- src/main/java/com/back/domain/board/post/repository/PostCategoryRepository.java
- src/main/java/com/back/domain/board/post/repository/PostRepositoryImpl.java
- src/main/java/com/back/domain/board/post/service/PostCategoryService.java
- src/main/java/com/back/global/exception/ErrorCode.java
- src/main/resources/application-dev.yml
- src/main/resources/application-test.yml
- src/main/resources/data.sql
- src/test/java/com/back/domain/board/controller/PostCategoryControllerTest.java
- src/test/java/com/back/domain/board/service/PostCategoryServiceTest.java
- 게시글 카테고리(`PostCategory`) 관련 기능을 추가했습니다.
- 엔티티 구조 수정, 초기 데이터 설정, 조회/생성 API 구현, Swagger 문서 및 테스트를 포함합니다.
* `PostCategory`에 `CategoryType`(enum) 필드 추가
* `CategoryType`: `SUBJECT`, `DEMOGRAPHIC`, `GROUP_SIZE`
* 생성자 오버로드(`name`, `name + type`)
* `data.sql`을 통해 90여 개의 기본 카테고리 자동 등록
* `application-dev.yml`에서 `defer-datasource-initialization: true`, `sql.init.mode: always` 설정
* **카테고리 전체 조회 (GET /api/posts/categories)**
* 모든 카테고리 반환
* `CategoryResponse`에 `type` 필드 포함
* **카테고리 생성 (POST /api/posts/categories)**
* 로그인 사용자만 등록 가능
* 중복 시 `409 Conflict`, 존재하지 않는 사용자 시 `404 Not Found` 처리
| 코드         | 상태  | 메시지              |
| ---------- | --- | ---------------- |
| `POST_003` | 404 | 존재하지 않는 카테고리입니다. |
| `POST_004` | 409 | 이미 존재하는 카테고리입니다. |
* `PostCategoryControllerDocs` 인터페이스 작성
* 요청/응답 예시 및 에러 …
> Feat: 카테고리 데이터 및 조회/생성 API 구현 (#196)

- src/main/java/com/back/domain/board/comment/controller/CommentLikeController.java
- src/main/java/com/back/domain/board/comment/controller/CommentLikeControllerDocs.java
- src/main/java/com/back/domain/board/comment/dto/CommentLikeResponse.java
- src/main/java/com/back/domain/board/comment/entity/Comment.java
- src/main/java/com/back/domain/board/comment/entity/CommentLike.java
- src/main/java/com/back/domain/board/comment/repository/CommentLikeRepository.java
- src/main/java/com/back/domain/board/comment/repository/CommentRepositoryImpl.java
- src/main/java/com/back/domain/board/comment/service/CommentLikeService.java
- src/main/java/com/back/global/exception/ErrorCode.java
- src/main/java/com/back/global/exception/GlobalExceptionHandler.java
- src/test/java/com/back/domain/board/controller/CommentLikeControllerTest.java
- src/test/java/com/back/domain/board/service/CommentLikeServiceTest.java
- 댓글에 대한 좋아요 및 좋아요 취소 기능을 구현했습니다.
- 좋아요 관련 API 전반(Controller, Service, Repository, DTO, Exception, Swagger, Test)을 포함합니다.
1. **Controller**
* `CommentLikeController` 추가
* `POST /api/posts/{postId}/comments/{commentId}/like`: 댓글 좋아요 등록
* `DELETE /api/posts/{postId}/comments/{commentId}/like`: 댓글 좋아요 취소
2. **Service**
* `CommentLikeService` 구현
* 사용자 및 댓글 검증 로직 추가
* 중복 좋아요 시 `COMMENT_005` 예외 발생
* 좋아요 취소 시 `COMMENT_006` 예외 처리 및 `likeCount` 감소 반영
3. **Repository**
* `CommentLikeRepository` 추가
* `existsByUserIdAndCommentId`, `findByUserIdAndCommentId` 메서드 구현
4. **Entity**
* `Comment` 엔티티에 `likeCount` 필드 추가 (`@Column(nullable = false, default = 0)`)
* `increaseLikeCount()`, `decreaseLikeCount()` 메서드 추가
5. **DTO**
* `CommentLikeResponse` 추가 (`commentId`, `likeCount` 반환)
6. **ErrorCode**
* …
> Feat: 댓글 좋아요/좋아요 취소 API 구현 (#181)

- src/main/java/com/back/domain/board/post/controller/PostLikeController.java
- src/main/java/com/back/domain/board/post/controller/PostLikeControllerDocs.java
- src/main/java/com/back/domain/board/post/dto/PostLikeResponse.java
- src/main/java/com/back/domain/board/post/entity/Post.java
- src/main/java/com/back/domain/board/post/entity/PostLike.java
- src/main/java/com/back/domain/board/post/repository/PostLikeRepository.java
- src/main/java/com/back/domain/board/post/repository/PostRepositoryImpl.java
- src/main/java/com/back/domain/board/post/service/PostLikeService.java
- src/main/java/com/back/global/exception/ErrorCode.java
- src/test/java/com/back/domain/board/controller/PostLikeControllerTest.java
- src/test/java/com/back/domain/board/service/PostLikeServiceTest.java
* 게시글에 대한 좋아요 및 좋아요 취소 기능을 구현했습니다.
* 좋아요 관련 API 전반(Controller, Service, Repository, DTO, Exception, Swagger, Test)을 포함합니다.
1. **Controller**
* `PostLikeController` 추가
* `POST /api/posts/{postId}/like`: 게시글 좋아요 등록
* `DELETE /api/posts/{postId}/like`: 게시글 좋아요 취소
2. **Service**
* `PostLikeService` 구현
* 사용자 및 게시글 검증 로직 추가
* 중복 좋아요 시 `POST_005` 예외 발생
* 좋아요 취소 시 `POST_006` 예외 처리 및 `likeCount` 감소 반영
3. **Repository**
* `PostLikeRepository` 추가
* `existsByUserIdAndPostId`, `findByUserIdAndPostId` 메서드 구현
4. **Entity**
* `Post` 엔티티에 `likeCount` 필드 추가 (`@Column(nullable = false)`)
* `increaseLikeCount()`, `decreaseLikeCount()` 메서드 추가
5. **DTO**
* `PostLikeResponse` 추가 (`postId`, `likeCount` 반환)
6. **ErrorCode**
* `POST_005`: 이미 좋아요한 게시글입니다.
* `POST_006`: 해당 게시글에 대한 좋아요 기록이 없습니다.
7. **Swagger 문서 …
> Feat: 게시글 좋아요/좋아요 취소 API 구현 (#201)
